inherit_gem:
  rubocul: rubocul_default.yml

AllCops:
  TargetRubyVersion: 3.3.7  # Update to your version of ruby

# For standalone Ruby scripts, we don't need the Rails cops that are built into rubocul, so we'll disable them.
Rails:
  Enabled: false
